shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"


# Base16 Spacemacs 256 - alacritty color config
# Nasser Alshammari (https://github.com/nashamri/spacemacs-theme)
colors:
  # Default colors
  primary:
    background: '0x1f2022'
    foreground: '0xa3a3a3'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1f2022'
    cursor: '0xa3a3a3'

  # Normal colors
  normal:
    black:   '0x1f2022'
    red:     '0xf2241f'
    green:   '0x67b11d'
    yellow:  '0xb1951d'
    blue:    '0x4f97d7'
    magenta: '0xa31db1'
    cyan:    '0x2d9574'
    white:   '0xa3a3a3'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xf2241f'
    green:   '0x67b11d'
    yellow:  '0xb1951d'
    blue:    '0x4f97d7'
    magenta: '0xa31db1'
    cyan:    '0x2d9574'
    white:   '0xf8f8f8'

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Bold
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono"
    style: Bold Italic

  size: 7

  offset:
    x: 0
    y: 2

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
