shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: "#000000"
    foreground: "#ffffff"

  cursor:
    text: '#000000'
    background: '#ffff00'

  normal:
    black: "#000000"
    red: "#ff8059"
    green: "#00fc50"
    yellow: "#eecc00"
    blue: "#29aeff"
    magenta: "#feacd0"
    cyan: "#00d3d0"
    white: "#eeeeee"

  bright:
    black:   '#555555'
    red:     '#ffa0a0'
    green:   '#88cf88'
    yellow:  '#d2b580'
    blue:    '#92baff'
    magenta: '#e0b2d6'
    cyan:    '#a0bfdf'
    white:   '#ffffff'

  dim:
    black:   '#222222'
    red:     '#fb6859'
    green:   '#00fc50'
    yellow:  '#ffdd00'
    blue:    '#00a2ff'
    magenta: '#ff8bd4'
    cyan:    '#30ffc0'
    white:   '#dddddd'

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Bold
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono"
    style: Bold Italic

  size: 7

  offset:
    x: 0
    y: 1

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
