shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: "#1D2021"
    foreground: "#EBDBD2"

  normal:
    black: "#1D2021"
    red: "#CC241D"
    green: "#98971A"
    yellow: "#D79921"
    blue: "#458588"
    magenta: "#B16286"
    cyan: "#689D6A"
    white: "#A89984"

  bright:
    black: "#928374"
    red: "#FB4934"
    green: "#B8BB26"
    yellow: "#FABD2F"
    blue: "#83a598"
    magenta: "#D3869B"
    cyan: "#8EC07C"
    white: "#EBDBB2"

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Bold
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono"
    style: Bold Italic

  size: 7

  offset:
    x: 0
    y: 1

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
