shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: '0x000000'
    foreground: '0xffffff'

  normal:
    black:   '0x000000'
    red:     '0xff8059'
    green:   '0x44bc44'
    yellow:  '0xd0bc00'
    blue:    '0x2fafff'
    magenta: '0xfeacd0'
    cyan:    '0x00d3d0'
    white:   '0xbfbfbf'

  bright:
    black:   '0x595959'
    red:     '0xef8b50'
    green:   '0x70b900'
    yellow:  '0xc0c530'
    blue:    '0x79a8ff'
    magenta: '0xb6a0ff'
    cyan:    '0x6ae4b9'
    white:   '0xffffff'

  selection:
    background: '0x264f78'
    foreground: CellForeground

font:
  normal:
    family: "Sarasa Mono SC"
    style: Regular
  bold:
    family: "Sarasa Mono SC"
    style: Bold
  italic:
    family: "Sarasa Mono SC"
    style: Italic
  bold_italic:
    family: "Sarasa Mono SC"
    style: Bold Italic

  size: 14

  offset:
    x: 0
    y: 2

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
