shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: '#ffffff'
    foreground: '#000000'

  normal:
    black:   '#ffffff'
    red:     '#cc342b'
    green:   '#198844'
    yellow:  '#fba922'
    blue:    '#3971ed'
    magenta: '#a36ac7'
    cyan:    '#3971ed'
    white:   '#c5c8c6'

  bright:
    black:   '#969896'
    red:     '#cc342b'
    green:   '#198844'
    yellow:  '#fba922'
    blue:    '#3971ed'
    magenta: '#a36ac7'
    cyan:    '#3971ed'
    white:   '#7276F8'

  selection:
    background: '#d5baff'
    foreground: CellForeground

font:
  size: 14

  offset:
    x: 0
    y: 2

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
