shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'

  normal:
    black:   '#000000'
    red:     '#ff8059'
    green:   '#44bc44'
    yellow:  '#d0bc00'
    blue:    '#2fafff'
    magenta: '#feacd0'
    cyan:    '#00d3d0'
    white:   '#bfbfbf'

  bright:
    black:   '#595959'
    red:     '#ef8b50'
    green:   '#70b900'
    yellow:  '#c0c530'
    blue:    '#79a8ff'
    magenta: '#b6a0ff'
    cyan:    '#6ae4b9'
    white:   '#ffffff'

  selection:
    background: '#264f78'
    foreground: CellForeground

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Bold
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono"
    style: Bold Italic

  size: 12

  offset:
    x: 0
    y: 2

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
