colors:

  primary:
    background: "#1C1E1F"
    foreground: "#D8DEE9"

  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#88C0D0"
    white: "#abb2bf"

  bright:
    black: "#5c6370"
    red: "#e06c75"
    green: "#98c379"
    yellow: "#d19a66"
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#ECEFF4"

background_opacity: 1.0

font:
  normal:
    family: "Sarasa Fixed Slab SC"
    style: Regular
  bold:
    family: "Sarasa Fixed Slab SC"
    style: Bold
  italic:
    family: "Sarasa Fixed Slab SC"
    style: Italic
  bold_italic:
    family: "Sarasa Term Slab SC"
    style: Bold Italic

  size: 12

  offset:
    x: 1
    y: 3

window:
  padding:
    x: 2
    y: 2

scrolling:
  history: 10000
  multiplier: 10

draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

key_bindings:
  - { key: V, mods: command, action: Paste }
  - { key: C, mods: command, action: Copy }
