shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: '#ffffff'
    foreground: '#000000'
  selection:
    text: CellForeground
    background: '#a5a5a5'
  normal:
    black:   '#000000'
    red:     '#a60000'
    green:   '#005e00'
    yellow:  '#fbb829'
    blue:    '#0031a9'
    magenta: '#721045'
    cyan:    '#00538b'
    white:   '#bfbfbf'
  bright:
    black:   '#595959'
    red:     '#972500'
    green:   '#315b00'
    yellow:  '#fed06e'
    blue:    '#2544bb'
    magenta: '#5317ac'
    cyan:    '#005a5f'
    white:   '#ffffff'

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Regular
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono"
    style: Italic

  size: 12

  offset:
    x: 0
    y: 2

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
