shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: "#1d2021"
    foreground: "#93a1a1"

  normal:
    black: "#002b36"
    red: "#dc322f"
    green: "#00ff00"
    yellow: "#b58900"
    blue: "#268bd2"
    magenta: "#6c71c4"
    cyan: "#2aa198"
    white: "#93a1a1"

  bright:
    black: "#657b83"
    red: "#dc322f"
    green: "#00ff00"
    yellow: "#b58900"
    blue: "#268bd2"
    magenta: "#6c71c4"
    cyan: "#2aa198"
    white: "#fdf6e3"

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Bold
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono"
    style: Bold Italic

  size: 7

  offset:
    x: 0
    y: 1

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
