shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

colors:
  primary:
    background: "#000000"
    foreground: "#ebdbb2"

  normal:
    black: "#000000"
    red: "#ff8059"
    green: "#44bc44"
    yellow: "#d0bc00"
    blue: "#2fafff"
    magenta: "#feacd0"
    cyan: "#00d3d0"
    white: "#a6a6a6"

  bright:
    black: "#595959"
    red: "#ef8b50"
    green: "#70b900"
    yellow: "#c0c530"
    blue: "#79a8ff"
    magenta: "#f78fe7"
    cyan: "#4ae2f0"
    white: "#ffffff"

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Bold
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono"
    style: Bold Italic

  size: 7

  offset:
    x: 0
    y: 1

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
