shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"


import:
  - /home/mackong/.config/alacritty/colors.yml

font:
  normal:
    family: "Noto Sans Mono"
    style: Regular
  bold:
    family: "Noto Sans Mono"
    style: Bold
  italic:
    family: "Noto Sans Mono"
    style: Italic
  bold_italic:
    family: "Mono Sans Mono"
    style: Bold Italic

  size: 8

  offset:
    x: 0
    y: 2

window:
  padding:
    x: 0
    y: 0

scrolling:
  history: 10000
  multiplier: 10

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
