allow_remote_control socket-only
listen_on unix:/tmp/kitty
enabled_layouts splits,stack
cursor_shape block
shell_integration no-cursor
scrollback_lines 10000
visual_bell_duration 0
enable_audio_bell no

tab_title_max_length 15
active_tab_foreground   #000
active_tab_background   #698dda
inactive_tab_foreground #fff
inactive_tab_background #000

font_size 16
adjust_line_height 2
font_family Aporetic Serif Mono
bold_font auto
italic_font auto
bold_italic_font auto
symbol_map U+3000-U+303F,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF,U+FE30-U+FE4F,U+FF00-U+FFEF LXGW WenKai

map ctrl+shift+p
map cmd+shift+v
map ctrl+shift+n
map cmd+n
map ctrl+shift+t
map cmd+t
map ctrl+shift+w
map cmd+w
map ctrl+shift+enter
map cmd+enter
map ctrl+shift+[
map ctrl+shift+]
map cmd+shift+[
map cmd+shift+]
map ctrl+shift+f
map ctrl+shift+b
map ctrl+shift+`
map ctrl+shift+r
map ctrl+shift+l
map ctrl+shift+page_up
map ctrl+shift+page_down
map ctrl+shift+tab
map ctrl+tab
map cmd+shift+left
map cmd+shift+right
map ctrl+shift+1
map ctrl+shift+2
map ctrl+shift+3
map ctrl+shift+4
map ctrl+shift+5
map ctrl+shift+6
map ctrl+shift+7
map ctrl+shift+8
map ctrl+shift+9
map cmd+equal
map cmd+minus
map cmd+0
map ctrl+shift+up
map ctrl+shift+down
map ctrl+shift+page_up
map ctrl+shift+page_down
map ctrl+shift+home
map ctrl+shift+end
map ctrl+shift+h
map cmd+shift+h
map ctrl+shift+space
map ctrl+shift+u
map ctrl+shift+escape
map cmd+ctrl+f
map cmd+shift+m
map cmd+shift+n
map ctrl+shift+p
map ctrl+shift+g

map ctrl+q>" launch --location=hsplit --cwd=current
map ctrl+q>% launch --location=vsplit --cwd=current
map ctrl+q>z toggle_layout stack

map ctrl+q>h neighboring_window left
map ctrl+q>j neighboring_window down
map ctrl+q>k neighboring_window up
map ctrl+q>l neighboring_window right

map ctrl+q>shift+h resize_window wider 5
map ctrl+q>shift+l resize_window narrower 5
map ctrl+q>shift+k resize_window shorter 5
map ctrl+q>shift+j resize_window taller 5

# Cmd+F -> ESC f
map cmd+f send_text all \x1bf
# Cmd+B -> ESC b
map cmd+b send_text all \x1bb
# Cmd+D -> ESC d
map cmd+d send_text all \x1bd
# Cmd+W -> ESC w
map cmd+w send_text all \x1bw

map ctrl+q>c new_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+shift+u kitten hints --type url --program @
map cmd+shift+p kitten hints --type path --program @
map cmd+shift+w kitten hints --type word --program @
map cmd+shift+l kitten hints --type line --program @
action_alias kitty_scrollback_nvim kitten '~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
map ctrl+q>[ kitty_scrollback_nvim
